import json
import logging
import re
from typing import Any, Dict

logger = logging.getLogger(__name__)


class JSONParseError(ValueError):
    """
    Custom exception raised when JSON parsing or repairing fails.
    """
    pass


class JSONParser:
    """
    Utility class to extract, clean, repair, and parse raw JSON strings returned by LLM models.
    """

    @classmethod
    def parse(cls, raw_text: str) -> Dict[str, Any]:
        """
        Extracts JSON from text block, performs structural repairs, and loads into a dictionary.

        Args:
            raw_text (str): Raw string returned from LLM.

        Returns:
            Dict[str, Any]: Python dictionary containing the parsed data.

        Raises:
            JSONParseError: If parsing fails even after attempted repairs.
        """
        logger.debug(f"Parsing raw text string (length: {len(raw_text)})")

        # 1. Clean external text surrounding the JSON block
        cleaned_block = cls.extract_json_block(raw_text)

        # 2. Try direct load
        try:
            return json.loads(cleaned_block)
        except json.JSONDecodeError as e:
            logger.warning(f"Initial JSON decode failed: {e}. Executing repair pipeline.")

        # 3. Apply structural repairs
        repaired_block = cls.repair_json(cleaned_block)

        # 4. Try parsing repaired JSON string
        try:
            return json.loads(repaired_block)
        except json.JSONDecodeError as e:
            logger.error(f"JSON parsing failed after applying repairs. Error: {e}\nRaw clean payload:\n{cleaned_block}")
            raise JSONParseError(
                f"Failed to parse and repair JSON string. Details: {e}"
            ) from e

    @classmethod
    def extract_json_block(cls, text: str) -> str:
        """
        Extracts JSON text from markdown code fences or locate structural bounds.
        """
        trimmed = text.strip()

        # Regex to match ```json { ... } ``` or ``` { ... } ```
        markdown_pattern = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", trimmed, re.DOTALL | re.IGNORECASE)
        if markdown_pattern:
            logger.debug("Found JSON block inside markdown code fences.")
            return markdown_pattern.group(1).strip()

        # Fallback: Find first '{' and last '}'
        first_brace = trimmed.find("{")
        last_brace = trimmed.rfind("}")

        if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
            logger.debug("Found JSON structure bounds by bracing.")
            return trimmed[first_brace:last_brace + 1].strip()

        return trimmed

    @classmethod
    def repair_json(cls, text: str) -> str:
        """
        Repairs common formatting issues inside JSON generated by LLMs:
        - Trailing commas inside objects and lists
        - Single quotes used as keys or value wrappers
        - Unescaped newlines inside string values
        """
        repaired = text

        # 1. Repair trailing commas in arrays/objects: e.g. [1, 2, ] -> [1, 2] or {"a": 1, } -> {"a": 1}
        repaired = re.sub(r",\s*([\}\]])", r"\1", repaired)

        # 2. Fix single quotes to double quotes for object keys
        repaired = re.sub(r"'\s*(\w+)\s*'\s*:", r'"\1":', repaired)

        # 3. Fix single quotes to double quotes for string values (not containing inner single quotes)
        repaired = re.sub(r":\s*'([^']*)'", r': "\1"', repaired)

        # 4. Escape raw newlines and carriage returns inside double-quoted string values
        chars = list(repaired)
        in_string = False
        escape_next = False
        
        for i in range(len(chars)):
            char = chars[i]
            
            if escape_next:
                escape_next = False
                continue
                
            if char == '\\':
                escape_next = True
                continue
                
            if char == '"':
                in_string = not in_string
                continue
                
            if in_string:
                if char == '\n':
                    chars[i] = '\\n'
                elif char == '\r':
                    chars[i] = '\\r'

        repaired = "".join(chars)

        return repaired
